### ISSUE TITLE
[4.3] Black Box Testing

### ISSUE THREAD

**Issue by vianiecetan** [samuelsongg/INF2001_P6-4#29]
Description:
- Decide on which use case to do black box testing on.
- Design decision table based on the use case. Identify causes, effects, and values for the table.
- Reduce the decision table.
- Come up with test cases.

Success Criteria:
Test cases designed and have tested all against the system.

Start Date:
13 Nov 2023

Allocated Time:
5 Days

Deadline:
17 Nov 2023

**Comment by samuelsongg** [comment]
Description:
Test cases have been successfully designed based on the decision table and use case.

Committed To Repo:
Nil

Task Completed On Time:
Yes

Are There Any Changes To The Completion Criteria Of The Task?:
No

Start Date:
13 Nov 2023

End Date:
17 Nov 2023

**Comment by vianiecetan** [comment]
Description:
Test cases have been successfully designed based on the decision table and use case.

Committed To Repo:
Nil

Task Completed On Time:
Yes

Are There Any Changes To The Completion Criteria Of The Task?:
No

Start Date:
13 Nov 2023

End Date:
17 Nov 2023
