### ISSUE TITLE
[4.2.1] Draw Design Pattern 1

### ISSUE THREAD

**Issue by Celeste45** [samuelsongg/INF2001_P6-4#36]
Description:
- Decide on which design pattern to implement with justifications.
- Integrate design pattern into the class diagram.

Success Criteria:
- Justify design pattern choice.
- Integration of design pattern makes logical sense.

Start Date:
6 Nov 2023

Allocated Time:
5 Days

Deadline:
10 Nov 2023

**Comment by samuelsongg** [comment]
Description:
- Design pattern choice has been justified.
- Design pattern has been integrated into class diagram.

Committed To Repo:
Nil

Task Completed On Time:
Yes

Are There Any Changes To The Completion Criteria Of The Task?:
No

Start Date:
6 Nov 2023

End Date:
10 Nov 2023

**Comment by Celeste45** [comment]
Description:
- Design pattern choice has been justified.
- Design pattern has been integrated into class diagram.

Committed To Repo:
Nil

Task Completed On Time:
Yes

Are There Any Changes To The Completion Criteria Of The Task?:
No

Start Date:
6 Nov 2023

End Date:
10 Nov 2023
