### ISSUE TITLE
What Went Well in Milestone 1?

### ISSUE THREAD

**Issue by Celeste45** [samuelsongg/INF2001_P6-4#40]
In Milestone 1, our team demonstrated a commendable level of proactivity and initiative. This positive attribute was noticeable across all team members as everyone consistently took the initiative to complete their assigned tasks. This not only reflects a strong sense of individual responsibility but also signifies a high level of commitment within the team. It's a promising foundation for our future project milestones.

**Comment by samuelsongg** [comment]
The team has shown that they are capable of producing work of high quality without the need to remind them of deadlines. The team also has minimal conflicts, if none at all. Everyone is open-minded and considers each other's suggestions thoughtfully, giving reasons why it may or may not work.
